server:
  port: 8088
  servlet:
    context-path: /dev


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scy?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.qq.com
    username: 1976886491@qq.com
    password: jfsqmedobnulbcje
    default-encoding: utf-8



